### ISSUE TITLE
Build issue with latest image

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-tezos#186] opened 2022-02-16 10:26 UTC

**Comment by becominginsane** [comment] 2022-03-11 19:19
Fixed by https://github.com/Zondax/ledger-tezos/pull/185, caused by https://github.com/Zondax/docker-rust-ci/commit/b8dc5d3315b5973f08a4ba0b620573d3be654006

**Closed by becominginsane** 2022-03-11 19:19 UTC
